# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4
#13/10/2023 1037

trigger:
- '*'
  # branches:
  #   include:
  #   - '*'
  # path:
  #   exclude:
  #   - documentos/*

pool:
  vmImage: 'ubuntu-20.04'
  demands:
  - npm

variables:
  buildConfig: 'Release'
  wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
  dotnetSdkVersion: '8.x'
  proyectosGral: '**/*.csproj'


steps:
- task: UseDotNet@2
  displayName: 'Usar SDK de .NET $(dotnetSdkVersion)'
  inputs:
    version: '$(dotnetSdkVersion)'

- task: Npm@1
  displayName: 'Instalar npm'
  inputs:
    verbose: false

- script: './node_modules/.bin/node-sass $(wwwrootDir) --output $(wwwrootDir)'
  displayName: 'Compilar Sass assets'

- task: gulp@1
  displayName: 'Correr tarea de gulp.'

- script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
  displayName: 'Información de compilación.'
  workingDirectory: $(wwwrootDir)

- task: DotNetCoreCLI@2
  displayName: 'Restaurar dependencias de proyecto'
  inputs:
    command: 'restore'
    projects: '$(proyectosGral)'

- task: DotNetCoreCLI@2
  displayName: 'Compilar el proyecto - $(buildConfig)'
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration $(buildConfig)'
    projects: '$(proyectosGral)'

- task: DotNetCoreCLI@2
  displayName: 'Publicar el proyecto - $(buildConfig)'
  inputs:
    command: 'publish'
    projects: '$(proyectosGral)'
    publishWebProjects: false
    arguments: '--no-build --configuration $(buildConfig) --output $(Build.ArtifactStagingDirectory)/$(buildConfig)'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: 'Publicar el artefacto: drop'
  condition: succeeded()