# Norbert
# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4
#13/10/2023 1037

trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'
  demands:
  - npm

variables:
  buildConfig: 'Release'
  wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
  dotnetSdkVersion: '8.x'
  proyectos: '**.*csproj'

steps:
- task: UseDotNet@2
  displayName: 'Usar el .net SDK: $(dotnetSdkVersion)'
  inputs:
    version: '$(dotnetSdkVersion)'

- task: Npm@1
  displayName: 'Instalar npm.'
  inputs:
    verbose: false

- Script: './node_modules/.bin/node-sass $(wwwrootDir) --output $(wwwrootDir)'
  displayName: 'Compile Sass assets'

- task: gulp@1
  displayName: 'Ejecutar tarea de gulp.'

- script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
  displayName: 'Escribir ingormación de compilado'
  workingDirectory: $(wwwrootDir)

- task: DotNetCoreCLI@2
  displayName: 'Restaurar dependencias de proyecto.'
  inputs:
    command: 'restore'
    projects: '$(proyectos)'

- task: DotNetCoreCLI@2
  displayName: 'Compilar el proyecto - $(buildConfig)'
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration $(buildConfig)'
    projects: '$(proyectos)'

- task: DotNetCoreCLI@2
  displayName: 'Publicar el proyecto - $(buildConfig)'
  inputs:
    command: 'publish'
    projects: '$(proyectos)'
    publicWebProjects: false
    arguments: '--no-build --configuration $(buildConfig) --output $(Build.ArtifactStagingDirectory)/$(buildConfig)'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: 'Publicar artefacto en drop.'
  confirm: succeeded()